Tiantian/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('tt_user.urls',namespace='user')),
    url(r'^',include('tt_goods.urls')),
    url(r'^cart/',include('tt_cart.urls')),
    url(r'^order/',include('tt_order.urls'))
]

tt_cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.cart),
    url(r'^add(\d+)_(\d+)/$',views.add),
    url(r'^edit(\d+)_(\d+)/$',views.edit),
    url(r'^delete(\d+)/$',views.delete),
]

tt_user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$', views.register,name='register'),
    url(r'^login/$', views.login,name='login'),
    url(r'^register_click/$', views.register_click,name='register_click'),
    url(r'^username_exist/$', views.username_exist,name='username_exist'),
    url(r'^login_click/$', views.login_click,name='login_click'),
    url(r'^loginout/$', views.loginout,name='loginout'),
    url(r'^info/$', views.info),
    url(r'^order(\d*)/$', views.order),
    url(r'^address/$', views.address),


]

tt_order/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class OrderInfo(models.Model):
    id=models.CharField(max_length=30, primary_key=True)
    user=models.ForeignKey('tt_user.User')
    createDate=models.DateTimeField(auto_now_add=True)
    expiredDate = models.DateTimeField()
    payType=models.CharField(max_length=2,default='1')
    orderState = models.CharField(max_length=2,default='1')# 1 未支付 2 已支付 3 已过期
    total=models.DecimalField(max_digits=6,decimal_places=2)
    address=models.CharField(max_length=150)


class OrderDetail(models.Model):
    goods=models.ForeignKey('tt_goods.GoodsDetail')
    order=models.ForeignKey(OrderInfo)
    price=models.DecimalField(max_digits=5,decimal_places=2)
    count=models.IntegerField()

tt_user/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class User(models.Model):

    uname = models.CharField(max_length=20,unique=True)
    upwd = models.CharField(max_length=50)
    uemail = models.CharField(max_length=30)
    uphone = models.CharField(max_length=11)
    uaddname = models.CharField(max_length=20, default='未填写')
    uaddress = models.CharField(max_length=50)
    upostcode = models.CharField(max_length=6)
    uaddressee = models.CharField(max_length=11)

tt_user/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from models import *
from hashlib import sha1
import user_verify
from tt_goods.models import *
from tt_order.models import *
from django.core.paginator import Paginator,Page
from datetime import datetime,timedelta

# Create your views here.

def register(request):

    return render(request,'tt_user/register.html')

def login(request):
    uname = request.COOKIES.get('uname', '')
    context = {'uname': uname}
    return render(request,'tt_user/login.html',context)


def register_click(request):

    uname = request.POST['user_name']
    upwd = request.POST['pwd']
    uapwd = request.POST['cpwd']
    uemail = request.POST['email']

    if uapwd == uapwd:
        hash = sha1()
        hash.update(upwd)
        hashpwd = hash.hexdigest()
        user = User()
        user.uname = uname
        user.upwd = hashpwd
        user.uemail = uemail
        user.save()
        return redirect('/user/login')
    else:
        return redirect('/user/register/')


def username_exist(request):
    uname = request.GET.get('user_name')
    count = User.objects.filter(uname=uname).count()
    if count:
        return JsonResponse({'code':200,'msg':'用户名已存在'})
    else:
        return JsonResponse({'code':300,'msg':'用户名可注册'})


def login_click(request):
    uname = request.POST['username']
    upwd = request.POST['pwd']
    ucheck = request.POST.get('checked')

    users = User.objects.filter(uname=uname)

    if len(users):
        hash = sha1()
        hash.update(upwd)
        if hash.hexdigest() == users[0].upwd:
            url = request.COOKIES.get('url', '/')
            red = HttpResponseRedirect(url)
            red.set_cookie('url', '', max_age=-1)
            # 记住用户名
            if ucheck :
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname', '', max_age=-1)
            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            return red
        else:
            context = {'code': '300', 'msg': '密码错误', 'uname': uname, 'upwd': upwd}
            print '密码错误'
            return render(request, 'tt_user/login.html', context)
    else:
        context = {'code': '300', 'msg': '用户名不存在', 'uname': uname, 'upwd': upwd}
        print '用户名不存在'
        return render(request, 'tt_user/login.html', context)

def loginout(request):
    request.session.flush()
    return redirect('/')


@user_verify.login
def info(request):
    user = User.objects.get(id=request.session['user_id'])

    goodsList = []
    goods_ids = request.COOKIES.get('goods_ids', '')
    if goods_ids != '':
        goods_ids1 = goods_ids.split(',')
        for goods_id in goods_ids1:
            goodsList.append(GoodsDetail.objects.get(id=int(goods_id)))

    context = {'user_email': user.uemail,
               'user_name': request.session['user_name'],
               'page_name': 1, # 隐藏购物车
               'user_phone':user.uphone,
               'goods_list': goodsList}
    return render(request, 'tt_user/user_center_info.html', context)



# 订单查询
@user_verify.login
def order(request,pindex):

    order_list = OrderInfo.objects.filter(user_id=request.session['user_id']).order_by('-id')
    for order in order_list:
        if order.orderState == '1' and order.expiredDate < datetime.now():
            order.orderState = '3'
    paginator = Paginator(order_list, 5)
    if pindex == '':
        pindex = '1'
    page = paginator.page(int(pindex))



    context = {'user_name': request.session['user_name'],
               'page_name': 1,
               'paginator': paginator,
               'page': page}
    return render(request, 'tt_user/user_center_order.html', context)

@user_verify.login
def address(request):
    user = User.objects.get(id=request.session['user_id'])

    if request.method == 'POST':
        user.uaddname = request.POST.get('uaddname')
        user.uaddress = request.POST.get('uaddress')
        user.uaddressee = request.POST.get('uaddressee')
        user.upostcode = request.POST.get('upostcode')
        user.save()

    context = {'user':user,'page_name': 1}

    return render(request, 'tt_user/user_center_site.html',context)

templates/tt_user/login.html
{%extends 'base_footer.html'%}


{% block title %} 天天生鲜-登录 {% endblock title %}

{% block body %}
	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_click/" method="post">
                        {%csrf_token%}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{uname}}">
						<div class="user_error"></div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码" value="{{upwd}}">
						<div class="pwd_error">{{ msg }}</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="checked" checked="checked" value="1">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	
{% endblock body %}

templates/tt_user/register.html
{% extends 'base_footer.html' %}


{% block title %}天天生鲜-注册{% endblock title %}

{% block head %}<script type="text/javascript" src="/static/js/register.js"></script>{% endblock head %}



{% block body %}

	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_click/" method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

{% endblock body %}

templates/tt_user/user_center_info.html
{%extends 'base.html'%}

{% block title %}个人信息{% endblock title %}
{%block content%}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/address/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user_name }}</li>
							<li><span>联系方式：</span>{{ user_phone|default:"未填写" }}</li>
							<li><span>邮箱：</span>{{ user_email|default:"未填写" }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">

{%for goods in goods_list%}
				<li>
					<a href="/{{goods.id}}/"><img src="/static/{{goods.pic}}"></a>
					<h4><a href="/{{goods.id}}/">{{goods.title}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{goods.price}}</span>
						<span class="unit">{{goods.price}}/{{goods.unit}}</span>
						<a href="/cart/add{{goods.id}}_1/" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
{%endfor%}

			</ul>
		</div>
		</div>
	</div>

{%endblock content%}


templates/tt_user/user_center_order.html
{%extends 'base.html'%}

{% block title %}全部订单{% endblock title %}

{%block content%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>

            <ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/" class="active">· 全部订单</a></li>
				<li><a href="/user/address/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>

        {% for order in page %}
				<ul class="order_list_th w978 clearfix">

					<li class="col01">{{order.createDate}}</li>
					<li class="col02">订单号：{{ order.id }}</li>
					<li class="col02 stress">{%if order.orderState == '1' %}待付款{% elif order.orderState == '2' %}已支付{% elif order.orderState == '3' %}已取消{% endif %}</li>

				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">


                                {%for detail in order.orderdetail_set.all%}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/{{detail.goods.pic}}"></li>
									<li class="col02">{{detail.goods.title}}<em>{{detail.goods.price}}元/{{detail.goods.unit}}</em></li>
									<li class="col03">{{detail.count}}</li>
									<li class="col04">{{detail.price}}元</li>
								</ul>

                                {% endfor %}
							</td>
							<td width="15%">{{order.total}}元</td>

                            {%if order.orderState == '1' %}
                                <td width="15%">待付款</td>
							    <td width="15%"><a href="/order/pay?id={{order.id}}&state=2" class="oper_btn">去付款</a></td>
                            {% elif order.orderState == '2' %}
                                <td width="15%">已支付</td>
							    <td width="15%"><a href="#" class="oper_btn">查看</a></td>
                            {% elif order.orderState == '3' %}
                                <td width="15%">已取消</td>
							    <td width="15%"><a href="#" class="oper_btn">查看</a></td>
                            {% endif %}

						</tr>
					</tbody>
				</table>
				

        {% endfor %}



				<div class="pagenation">

                    {% if page.has_previous %}
                    <a href="/user/order{{page.previous_page_number}}/"><上一页</a>
                    {% endif %}

                    {%for pindex in paginator.page_range%}
                        {%if pindex == page.number%}
                        <a href="#" class="active">{{pindex}}</a>
                        {%else%}
                        <a href="/user/order{{pindex}}/">{{pindex}}</a>
                        {%endif%}
                    {%endfor%}

                    {%if page.has_next%}
                        <a href="/user/order{{page.next_page_number}}/">下一页></a>
                    {%endif%}

				</div>
		</div>
	</div>



{%endblock content%}

templates/tt_user/user_center_site.html
{%extends 'base.html'%}

{% block title %}收货地址{% endblock title %}
{%block content%}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
                <li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/address/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.uaddress | default:'地址未填写' }} （{{ user.uaddname }} 收） {{ user.uaddressee|default:'收件人手机号未填写' }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/address/" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="uaddname" value="{{ user.uaddname }}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress">{{ user.uaddress }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="upostcode" value="{{ user.upostcode }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uaddressee" value="{{ user.uaddressee }}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>



{%endblock content%}